#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - mkdir -p /home/ubuntu/esdata
  - chown ubuntu:ubuntu /home/ubuntu/esdata
  - sysctl -w vm.max_map_count=262144
  - echo 'vm.max_map_count=262144' >> /etc/sysctl.conf